stages:
  - build

variables:
  IMAGE: eljojo/nara/nara-app
  DOCKER_CLI_EXPERIMENTAL: enabled

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  tags:
    - docker-images
  stage: build
  script:
    - docker build --build-arg opts="CGO_ENABLED=0 GOARCH=amd64" --pull -t $CI_REGISTRY/$IMAGE:amd64 .
    - docker push $CI_REGISTRY/$IMAGE:amd64
    - docker build --build-arg opts="GOARCH=arm64" --pull -t $CI_REGISTRY/$IMAGE:arm64 .
    - docker push $CI_REGISTRY/$IMAGE:arm64
    - docker manifest create $CI_REGISTRY/$IMAGE $CI_REGISTRY/$IMAGE:amd64 $CI_REGISTRY/$IMAGE:arm64
    - docker manifest annotate $CI_REGISTRY/$IMAGE $CI_REGISTRY/$IMAGE:arm64 --os linux --arch arm64
    - docker manifest push $CI_REGISTRY/$IMAGE
