#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const webRoot = path.resolve(__dirname, "..");
const srcRoot = path.join(webRoot, "src");
const outputPath = path.join(srcRoot, "generated", "iconoir.css");
const iconoirPath = path.join(webRoot, "..", "node_modules", "iconoir", "css", "iconoir.css");

function walk(dir, exts, out = []) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(fullPath, exts, out);
      continue;
    }
    const ext = path.extname(entry.name).toLowerCase();
    if (exts.has(ext)) {
      out.push(fullPath);
    }
  }
  return out;
}

function collectIconNames() {
  const files = walk(srcRoot, new Set([".js", ".jsx", ".ts", ".tsx", ".html"]));
  const iconNames = new Set();
  const regex = /iconoir-[a-z0-9-]+/g;
  for (const file of files) {
    const contents = fs.readFileSync(file, "utf8");
    const matches = contents.match(regex);
    if (!matches) continue;
    for (const name of matches) {
      iconNames.add(name);
    }
  }
  return Array.from(iconNames).sort();
}

function loadIconoirRules() {
  const css = fs.readFileSync(iconoirPath, "utf8");
  const firstRuleIndex = css.indexOf(".iconoir-");
  const header = firstRuleIndex === -1 ? css : css.slice(0, firstRuleIndex);
  const ruleRegex = /\.iconoir-([a-z0-9-]+)::before\{[^}]*\}/g;
  const rules = new Map();
  let match;
  while ((match = ruleRegex.exec(css)) !== null) {
    rules.set(match[1], match[0]);
  }
  return { header, rules };
}

function buildSubset() {
  if (!fs.existsSync(iconoirPath)) {
    console.error(`iconoir.css not found at ${iconoirPath}`);
    process.exit(1);
  }

  const iconNames = collectIconNames();
  const { header, rules } = loadIconoirRules();

  let output = "";
  output += "/* Auto-generated by nara-web/scripts/build-iconoir.js */\n";
  output += header.trimEnd();
  output += "\n";

  const missing = [];
  for (const name of iconNames) {
    const key = name.replace(/^iconoir-/, "");
    const rule = rules.get(key);
    if (!rule) {
      missing.push(name);
      continue;
    }
    output += `${rule}\n`;
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output, "utf8");

  if (missing.length > 0) {
    console.warn(`Missing icon rules for: ${missing.join(", ")}`);
  }

  console.log(`Wrote ${outputPath} with ${iconNames.length - missing.length} icons.`);
}

buildSubset();
